name: gofmt Linting

on:
  push:
    branches:
      - master

jobs:
  goLint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Lint
        run: |
          gofmt -l -s -w .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'RoseLoverX: auto Linting'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ivanezko
          commit_user_email: 72609355+ivanezko@users.noreply.github.com
          commit_author: ivanezko <72609355+ivanezko+@users.noreply.github.com>
